In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, accuracy_score

In [2]:
data = {
    'Name of Country': ['China', 'US', 'India', 'Japan', 'Germany', 'Brazil', 'Indonesia', 'Russia', 'UK', 'France'],
    'Country_wise_plastic_waste': [59.05, 42.02, 26.33, 7.99, 6.28, 5.96, 5.85, 5.84, 5.03, 4.98],
    'Main_source': ['Packaging_Industrial', 'Packaging_consumer', 'Consumer_goods', 'Packaging_Electronics', 
                    'Automotive_Packaging', 'Consumer_Packaging', 'Food_Packaging', 'Industrial_Consumer', 
                    'Packaging_consumer', 'Packaging_consumer'],
    'Recycling_Rate': [29.8, 32.1, 11.5, 84.8, 56.1, 1.2, 11.8, 5.6, 46.2, 27.3],
    'Per_capital_waste': [41.2, 127.5, 19.3, 63.2, 75.6, 28.1, 21.3, 40.2, 74.3, 73.1],
    'Coastal_Waste': ['High', 'Medium', 'High', 'Medium', 'Low', 'Medium', 'Very_High', 'Medium', 'Low', 'Low']
}

df = pd.DataFrame(data)

In [3]:
le = LabelEncoder()
df['Main_source'] = le.fit_transform(df['Main_source'])
df['Coastal_Waste'] = le.fit_transform(df['Coastal_Waste'])


In [4]:
X = df[['Country_wise_plastic_waste', 'Main_source', 'Recycling_Rate', 'Per_capital_waste']]
y = df['Coastal_Waste']

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [6]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [7]:
knn = KNeighborsClassifier(n_neighbors=3)  
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [8]:
y_pred = knn.predict(X_test)

In [9]:
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)



In [10]:
print("Accuracy:", accuracy)
print("Confusion Matrix:\n", conf_matrix)

Accuracy: 0.0
Confusion Matrix:
 [[0 0 0]
 [0 0 1]
 [1 0 0]]


In [11]:
y_pred_labels = le.inverse_transform(y_pred)
print("Predicted Coastal Waste Categories:", y_pred_labels)

Predicted Coastal Waste Categories: ['Medium' 'High']


In [ ]:
from sklearn import preprocessing
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.model_selection import train_test_split

# Data
Weather = ['Sunny', 'Sunny', 'Overcast', 'Rainy', 'Rainy', 'Rainy', 'Overcast', 'Sunny', 'Sunny', 'Rainy', 'Sunny', 'Overcast', 'Overcast', 'Rainy'] 
Temperature = ['Hot', 'Hot', 'Hot', 'Mild', 'Cold', 'Cold', 'Cold', 'Mild', 'Cold', 'Mild', 'Mild', 'Mild', 'Hot', 'Mild']
Play = ['No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No']

# Creating labelEncoder
le = preprocessing.LabelEncoder()

# Converting string into numbers for features
Weather_encoded = le.fit_transform(Weather)
Temperature_encoded = le.fit_transform(Temperature)

# Converting string into numbers for target variable
Play_encoded = le.fit_transform(Play)

# Creating features by zipping the encoded features
features = list(zip(Weather_encoded, Temperature_encoded))

# Splitting the dataset into training and testing sets
features_train, features_test, label_train, label_test = train_test_split(features, Play_encoded, test_size=0.2, random_state=42)

# Creating and training the KNN model
model = KNeighborsClassifier(n_neighbors=3, metric='euclidean')
model.fit(features_train, label_train)

# Making predictions
predicted = model.predict(features_test)

# Output predictions
print("Prediction:", predicted)

# Confusion Matrix
conf_mat = confusion_matrix(label_test, predicted)
print("Confusion Matrix:")
print(conf_mat)

# Accuracy
accuracy = accuracy_score(label_test, predicted)
print("Accuracy:", accuracy)

In [4]:
import numpy as np
train_points =np.array([[7,7],[7,4],[3,4],[1,4]])
train_labels=['Bad','Bad','Good','Good']
query_point=np.array([3,7])
distances= np.linalg.norm(train_points - query_point, axis=1)
nearest_indices = distances.argsort()[:3]
nearest_labels =[train_labels[i] for i in nearest_indices]
prediction = max(set(nearest_labels), key=nearest_labels.count)
print("Predication:",prediction)


Predication: Good
